import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';

/** Shared flat config. Apps extend this; they do not add a second policy. */
export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/.source/**',
      '**/coverage/**',
      // Pagefind build output (regenerated by `pnpm --filter @corpus/web build`
      // via the postbuild hook). It's third-party runtime code — ESLint walks
      // public/ for hand-authored assets (robots.txt, OG images), but the
      // pagefind subdirectory is auto-generated and not in the project source.
      '**/public/pagefind/**',
      'content/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    languageOptions: {
      globals: { ...globals.node },
    },
  },
);
