// AUTO-GENERATED by scripts/build-answer-keys.mjs — DO NOT EDIT.
// Source: every YAML in curation/overrides/, parsed at build time.
// Consumed by apps/web/lib/{quiz,dragdrop}-actions.ts (Server Actions).
// The static import means Turbopack bundles this module into the
// Lambda — no fs read at request time, so Vercel's serverless runtime
// can resolve it (catalog.json + curation YAMLs are not in the bundle).
// Schema: see packages/content-schema/src/{sidecars,dragdrop-sidecar}.ts.

export const answerKeys = {
  "articleUids": [
    "react/component-composition",
    "react/components-and-props",
    "react/conditional-rendering-and-events",
    "react/jsx-and-rendering",
    "react/rules-of-react",
    "react/thinking-in-react"
  ],
  "byArticle": {
    "react/component-composition": {
      "quiz": {
        "cc-owner-of-closure": {
          "correctLabel": "B",
          "explanation": "Owners supply the props and closures; parents supply the slot. Since `<Reports/>` was\nwritten inside `Page`'s render, the closure belongs to `Page`. Composition's whole\njob is making this distinction matter — by choosing where elements are *created*\n(the owner) versus where they're *emitted* (the parent), you decide whose state\nthey capture and whose re-renders they answer to.\n",
          "validLabels": [
            "A",
            "B",
            "C",
            "D"
          ]
        },
        "cc-slot-content": {
          "correctLabel": "B",
          "explanation": "A slotted element lives a double life. Props and closures come from the owner\n(captured at render-time); context comes from where it sits in the tree at render\nposition. The two are independent — and that independence is the mechanism compound\ncomponents are built on: the parts read the family's context because the caller\nplaced them inside it.\n",
          "validLabels": [
            "A",
            "B",
            "C",
            "D"
          ]
        },
        "cc-lift-content-up": {
          "correctLabel": "B",
          "explanation": "`ResizableSplit` re-renders per drag frame, but its render function only emits\n`{left}` and `{right}` — those elements were created in the *caller's* render, so they\nkeep the same reference across every ResizableSplit render. React's bailout check sees\nidentical element refs and skips the subtree entirely. The anti-version is\n`ResizableSplit` importing `<FileTree />` itself — owner moves, bailout gone.\n",
          "validLabels": [
            "A",
            "B",
            "C",
            "D"
          ]
        },
        "cc-controlled-vs-uncontrolled": {
          "correctLabel": "B",
          "explanation": "The presence of `value` selects controlled mode; absence selects uncontrolled (with\n`defaultValue` as the seed). In controlled mode, the root fires the callback but never\nwrites its own state — the caller owns the truth. In uncontrolled mode, the root owns\nstate but the callback is optional. Switching modes mid-life is the same bug it was\nfor inputs: state writes during a 'controlled' render corrupt the source of truth.\n",
          "validLabels": [
            "A",
            "B",
            "C",
            "D"
          ]
        }
      },
      "dragdrop": {
        "cc-render-props-vs-hook": {
          "sidecarId": "cc-render-props-vs-hook",
          "mode": "exact",
          "slots": [
            {
              "id": "cc-slot-hook",
              "label": "Custom hook",
              "accepts": [
                "cc-chip-form",
                "cc-chip-validation"
              ]
            },
            {
              "id": "cc-slot-rp",
              "label": "Render prop",
              "accepts": [
                "cc-chip-vlist",
                "cc-chip-tooltip"
              ]
            }
          ],
          "chips": [
            {
              "id": "cc-chip-form",
              "text": "useFormField in a form",
              "correctSlots": [
                "cc-slot-hook"
              ]
            },
            {
              "id": "cc-chip-validation",
              "text": "useDebouncedValue",
              "correctSlots": [
                "cc-slot-hook"
              ]
            },
            {
              "id": "cc-chip-vlist",
              "text": "<VirtualList renderRow=...>",
              "correctSlots": [
                "cc-slot-rp"
              ]
            },
            {
              "id": "cc-chip-tooltip",
              "text": "<Chart data renderLegend=...>",
              "correctSlots": [
                "cc-slot-rp"
              ]
            }
          ],
          "explanation": "Custom hooks win when the caller reuses the *logic*. Render props win when the component owns per-instance data (positions, measurements, virtualized rows) and the caller owns the markup. Function-as-children is the same pattern with `children` as the function — fine, but named props like `renderRow` read better once there's more than one."
        }
      }
    },
    "react/components-and-props": {
      "quiz": {
        "cap-fresh-literal-memo": {
          "correctLabel": "B",
          "explanation": "`Object.is` is per-value, not deep. Two structurally-equal fresh objects compare as\ndifferent. The fix is to lift the object out of render (`useMemo`, a `const` at module\nscope, or a `useState` that holds the shape) so the reference is stable across renders.\n",
          "validLabels": [
            "A",
            "B",
            "C",
            "D"
          ]
        },
        "cap-mutated-array": {
          "correctLabel": "B",
          "explanation": "Two consequences from one bug. (1) Purity contract violated: a render mutating inputs\nisn't repeatable or discardable. (2) `Object.is` says the array is the same reference it\nwas before the sort, so any skip-render logic (memo, useState bailouts) sees no change.\nUse `toSorted()` or copy first.\n",
          "validLabels": [
            "A",
            "B",
            "C",
            "D"
          ]
        },
        "cap-memo-with-children": {
          "correctLabel": "B",
          "explanation": "Every render of the parent evaluates its JSX, which creates new element objects for\nevery child — including `<Reports />` in `<HeavyPanel><Reports/></HeavyPanel>`. The\nnew element becomes a new `props.children` reference, the shallow compare fails, and\nthe memo pays for nothing. Composition fixes this by pushing the ticking state *down*\ninto a child component so the heavy subtree is created by something that isn't\nre-rendering.\n",
          "validLabels": [
            "A",
            "B",
            "C",
            "D"
          ]
        },
        "cap-push-state-down": {
          "correctLabel": "C",
          "explanation": "`useMemo(() => <Reports />, [])` looks right but the empty-deps array lies: `<Reports/>`\nis still re-created every time the parent runs, just to be thrown away. The structural\nfix is what the article calls \"push state down, pull content up\" — `ClockSection`\nowns the tick state and accepts the heavy subtree as children, so its render reuses\nthe same `<Reports/>` element reference and React bails out of the subtree entirely.\n",
          "validLabels": [
            "A",
            "B",
            "C",
            "D"
          ]
        }
      },
      "dragdrop": {
        "cap-common-mistakes": {
          "sidecarId": "cap-common-mistakes",
          "mode": "exact",
          "slots": [
            {
              "id": "cap-slot-mutation",
              "label": "Mutating props",
              "accepts": [
                "cap-mut-tosorted",
                "cap-mut-spread"
              ]
            },
            {
              "id": "cap-slot-leaky",
              "label": "Leaky DOM props",
              "accepts": [
                "cap-leak-destructure",
                "cap-leak-warning"
              ]
            },
            {
              "id": "cap-slot-booleans",
              "label": "Boolean pile",
              "accepts": [
                "cap-bool-union",
                "cap-bool-disable"
              ]
            }
          ],
          "chips": [
            {
              "id": "cap-mut-tosorted",
              "text": "toSorted() or copy first",
              "correctSlots": [
                "cap-slot-mutation"
              ]
            },
            {
              "id": "cap-mut-spread",
              "text": "Spread rest",
              "correctSlots": []
            },
            {
              "id": "cap-leak-destructure",
              "text": "Destructure out, spread rest",
              "correctSlots": [
                "cap-slot-leaky"
              ]
            },
            {
              "id": "cap-leak-warning",
              "text": "Run console.warn",
              "correctSlots": []
            },
            {
              "id": "cap-bool-union",
              "text": "Variant union",
              "correctSlots": [
                "cap-slot-booleans"
              ]
            },
            {
              "id": "cap-bool-disable",
              "text": "Disable the prop",
              "correctSlots": []
            }
          ],
          "explanation": "The mutations category points to `toSorted()` or copy first. The leaky props category points to destructure-then-spread. The boolean pile category points to a variant union. The reference-defeats-memo category points to lifting out of render. The introspection category points to explicit slots or context between compound parts."
        }
      }
    },
    "react/conditional-rendering-and-events": {
      "quiz": {
        "cre-and-zero-bug": {
          "correctLabel": "B",
          "explanation": "`&&` is a strict boolean short-circuit — `0 && X` evaluates to `0`, and `0` is a number\nReact happily renders (as the text \"0\"). The fix is the explicit guard\n`order.count > 0 && <Badge .../>` or the boolean coercion `Boolean(order.count) && ...`,\nwhich makes the intent obvious in review.\n",
          "validLabels": [
            "A",
            "B",
            "C",
            "D"
          ]
        },
        "cre-hooks-before-guard": {
          "correctLabel": "B",
          "explanation": "Hooks are matched by call order on the fiber. A `return` above a `useState` makes that\nhook conditional, and on the render where the guard flips, every subsequent hook\nshifts up by one — corrupting the entire list. The discipline is hooks first, guards\nsecond, JSX last; the ESLint rule catches the most common forms, but conditional\nhooks inside a switch with early returns is the case that still slips through.\n",
          "validLabels": [
            "A",
            "B",
            "C",
            "D"
          ]
        },
        "cre-target-vs-currenttarget": {
          "correctLabel": "B",
          "explanation": "`e.currentTarget` is the element you attached the handler to — always the button,\nalways typed (`HTMLButtonElement`). `e.target` is whatever was actually hit — the\nicon, the inner span, anything below — and it's loosely typed (`EventTarget`) so\nreading `dataset` from it warns. If you need the button's data, use `currentTarget`;\nif you need to know what specifically was clicked (for analytics, for hitting-test\ndelegation), use `target`.\n",
          "validLabels": [
            "A",
            "B",
            "C",
            "D"
          ]
        },
        "cre-stopprop-breaks-analytics": {
          "correctLabel": "B",
          "explanation": "Since React 17 the root listener sits on the *container*, but the native event still\nbubbles upward from the actual DOM target — and `stopPropagation` in a React handler\nalso stops the native event. Anything above the React root (document-level\nanalytics, outside-click handlers, future libraries you didn't know were there) goes\nsilent. The article's advice: check `e.target` in the outer handler (`if\n(ref.current?.contains(e.target as Node)) return`), stop propagation only for a\nboundary you own and document.\n",
          "validLabels": [
            "A",
            "B",
            "C",
            "D"
          ]
        }
      },
      "dragdrop": {
        "cre-classify-mistakes": {
          "sidecarId": "cre-classify-mistakes",
          "mode": "exact",
          "slots": [
            {
              "id": "cre-slot-onclick",
              "label": "Inline arrow handler",
              "accepts": [
                "cre-chip-call",
                "cre-chip-usecallback"
              ]
            },
            {
              "id": "cre-slot-hooks",
              "label": "Hooks first",
              "accepts": [
                "cre-chip-guard",
                "cre-chip-early"
              ]
            },
            {
              "id": "cre-slot-blur",
              "label": "Idempotent commit",
              "accepts": [
                "cre-chip-onblur",
                "cre-chip-onescape"
              ]
            }
          ],
          "chips": [
            {
              "id": "cre-chip-call",
              "text": "`onClick={() => save(id)}` instead of `onClick={save(id)}`",
              "correctSlots": [
                "cre-slot-onclick"
              ]
            },
            {
              "id": "cre-chip-usecallback",
              "text": "Wrap in `useCallback`",
              "correctSlots": []
            },
            {
              "id": "cre-chip-guard",
              "text": "Move `useState`/`useEffect` above `if (!user) return null`",
              "correctSlots": [
                "cre-slot-hooks"
              ]
            },
            {
              "id": "cre-chip-early",
              "text": "Add a top-level early return",
              "correctSlots": []
            },
            {
              "id": "cre-chip-onblur",
              "text": "`onBlur` commit is idempotent; blur fires after button click",
              "correctSlots": [
                "cre-slot-blur"
              ]
            },
            {
              "id": "cre-chip-onescape",
              "text": "Add an Escape handler",
              "correctSlots": []
            }
          ],
          "explanation": "Calling instead of passing is fixed by an inline arrow. Guard clauses above hooks is fixed by moving hooks before the early return. Treating `onChange` as commit is fixed by putting validation in `onBlur`/`onSubmit`. `e.target` confusion is fixed by reading `e.currentTarget` for the attached element. Save-on-blur eating buttons needs the commit to be idempotent or the input to delay the blur handler until click."
        }
      }
    },
    "react/jsx-and-rendering": {
      "quiz": {
        "jsx-as-sugar-call": {
          "correctLabel": "C",
          "explanation": "Capitalization is semantic, not stylistic. JSX's compile target is `jsx(type, props)`:\nlowercase `<card>` would compile to `jsx('card', ...)` (a string — a host DOM tag),\nbut `<Card>` compiles to `jsx(Card, ...)` where the function itself is passed by reference.\nThe runtime decides \"is this an HTML tag (string) or a user component (function)\" at render time.\n",
          "validLabels": [
            "A",
            "B",
            "C",
            "D"
          ]
        },
        "jsxs-vs-jsx": {
          "correctLabel": "C",
          "explanation": "The `s` means *static children*. The compiler is vouching it built the array from your\nsource, so it can never reorder, so React skips the key check. Dynamic arrays from `.map`\n(runtime-built, possibly reordered) need the warning and go through plain `jsx()`.\n",
          "validLabels": [
            "A",
            "B",
            "C",
            "D"
          ]
        },
        "cart-zero-bug": {
          "correctLabel": "C",
          "explanation": "`children` accepts elements, arrays, strings, and numbers. `null` / `undefined` /\n`true` / `false` are the \"render nothing\" family and are flattened away — but numbers\nrender. The convention: comparisons, not truthiness, whenever the left side can be a\nnumber — `{cart.items.length > 0 && <CartBadge />}`. Same failure mode with `NaN`.\n",
          "validLabels": [
            "A",
            "B",
            "C",
            "D"
          ]
        },
        "key-not-in-props": {
          "correctLabel": "C",
          "explanation": "The transform emits `key` as a separate argument to `jsx(Item, props, key)`, and React\nstores it on the element, never in `props`. By the time your function runs, reconciliation\nalready spent it. That is why reading `props.key` inside a component logs a warning and\nyields `undefined`.\n",
          "validLabels": [
            "A",
            "B",
            "C",
            "D"
          ]
        },
        "inline-component-focus-loss": {
          "correctLabel": "B",
          "explanation": "Reconciliation matches positions by `type` reference. A new function identity each render\nmeans \"different component\", so React unmounts the old and mounts the new, destroying all\nstate including focus. The fix is always the same: hoist the inner component to module\nscope and pass data via props.\n",
          "validLabels": [
            "A",
            "B",
            "C",
            "D"
          ]
        },
        "element-not-yet-called": {
          "correctLabel": "B",
          "explanation": "An element is a description — `{ type: Card, props: { title: 'Hi' }, key: ... }` sitting\nin memory. The function has not been called yet. React calls it later, during render,\nagainst its own instance (the fiber) that tracks its position in the tree.\n",
          "validLabels": [
            "A",
            "B",
            "C",
            "D"
          ]
        }
      },
      "dragdrop": {
        "jsx-to-createelement": {
          "sidecarId": "jsx-to-createelement",
          "mode": "exact",
          "slots": [
            {
              "id": "type-slot",
              "label": "type",
              "accepts": [
                "jsx-component-ref",
                "jsx-component-string"
              ]
            },
            {
              "id": "props-slot",
              "label": "props",
              "accepts": [
                "jsx-component-ref",
                "props-object",
                "props-string"
              ]
            }
          ],
          "chips": [
            {
              "id": "jsx-component-ref",
              "text": "Card",
              "correctSlots": [
                "type-slot"
              ]
            },
            {
              "id": "jsx-component-string",
              "text": "'card'",
              "correctSlots": []
            },
            {
              "id": "props-object",
              "text": "{ title: 'Hi' }",
              "correctSlots": [
                "props-slot"
              ]
            },
            {
              "id": "props-string",
              "text": "title: 'Hi'",
              "correctSlots": []
            },
            {
              "id": "jsx-lowercase",
              "text": "card",
              "correctSlots": []
            },
            {
              "id": "props-null",
              "text": "null",
              "correctSlots": []
            },
            {
              "id": "props-array",
              "text": "['Hi']",
              "correctSlots": []
            }
          ],
          "explanation": "<Card> is capitalized, so JSX compiles to jsx(Card, { title: \"Hi\" }) — Card is the component function itself, passed by reference. The second arg is the props object. jsx('card', ...) would only be correct if card were lowercase (a DOM tag)."
        }
      }
    },
    "react/rules-of-react": {
      "quiz": {
        "ror-math-random-in-render": {
          "correctLabel": "B",
          "explanation": "`Math.random()` in render makes the component non-idempotent — StrictMode's double render\nproduces two different values, and concurrent discard/replay makes the result fiction.\nThe right home for \"value depends on a user action\" is the event handler that performs\nthe action. The right home for \"value sampled once at mount\" is a lazy initializer\n(`useState(() => Math.random())`). `useMemo` around it doesn't help — it caches an\narbitrary one of the random values.\n",
          "validLabels": [
            "A",
            "B",
            "C",
            "D"
          ]
        },
        "ror-hook-order-try-catch": {
          "correctLabel": "B",
          "explanation": "Hooks are matched to their fiber slots purely by call order. A throw between two hook\ncalls is functionally identical to a conditional early return — the next hook call\ndoesn't happen, the list shifts by one, the next render's list doesn't line up, and\nReact throws. The right answer is an error boundary above the component, not a\ntry/catch around the hook.\n",
          "validLabels": [
            "A",
            "B",
            "C",
            "D"
          ]
        },
        "ror-statusbadge-call": {
          "correctLabel": "B",
          "explanation": "Components are fibers, not just render outputs. When you call `StatusBadge(...)` directly,\nany hooks inside it register on the *current* fiber (the parent) — not on a StatusBadge\nfiber of their own. That breaks the hook-list contract for everyone who shares this\nrender. The fix is two characters of JSX: `<StatusBadge status={invoice.status} />` —\nJSX creates an element that React can mount as its own fiber.\n",
          "validLabels": [
            "A",
            "B",
            "C",
            "D"
          ]
        },
        "ror-render-tally": {
          "correctLabel": "B",
          "explanation": "Two problems from one violation. (1) Module-level write during render — two mounted\npanels now share one corrupted counter, and the count reflects any concurrent\nretry/discard, not the user's actual render count. (2) Renders must be discardable:\nconcurrent rendering can decide 'actually don't ship this render' and replay, and any\nexternal write makes that impossible to undo. The honest homes for render counts are\nthe Profiler (dev-time) or an effect (commits, not attempts).\n",
          "validLabels": [
            "A",
            "B",
            "C",
            "D"
          ]
        }
      },
      "dragdrop": {
        "ror-classify-mistakes": {
          "sidecarId": "ror-classify-mistakes",
          "mode": "exact",
          "slots": [
            {
              "id": "ror-slot-render-count",
              "label": "Use Profiler",
              "accepts": [
                "ror-chip-count",
                "ror-chip-console"
              ]
            },
            {
              "id": "ror-slot-strictmode",
              "label": "Make it symmetric",
              "accepts": [
                "ror-chip-disable",
                "ror-chip-effect"
              ]
            },
            {
              "id": "ror-slot-factory",
              "label": "Branch inside one hook",
              "accepts": [
                "ror-chip-factory",
                "ror-chip-loop"
              ]
            }
          ],
          "chips": [
            {
              "id": "ror-chip-count",
              "text": "`let renderTally = 0` + `renderTally++` in body",
              "correctSlots": [
                "ror-slot-render-count"
              ]
            },
            {
              "id": "ror-chip-console",
              "text": "console.log('rendered') in body",
              "correctSlots": []
            },
            {
              "id": "ror-chip-disable",
              "text": "Disable StrictMode to silence the doubling",
              "correctSlots": [
                "ror-slot-strictmode"
              ]
            },
            {
              "id": "ror-chip-effect",
              "text": "Add an effect that runs once",
              "correctSlots": []
            },
            {
              "id": "ror-chip-factory",
              "text": "`const useThing = flags.x ? useA : useB`",
              "correctSlots": [
                "ror-slot-factory"
              ]
            },
            {
              "id": "ror-chip-loop",
              "text": "`hooks[name]()` from a dynamic registry",
              "correctSlots": [
                "ror-slot-factory"
              ]
            }
          ],
          "explanation": "Render-count refs → use the Profiler. Suppressing the hooks lint → fix the deps. Shallow-spread laundering → copy the nested mutation too. Memoizing impurity → move randomness/time to its right room first. Hook factories → branch inside one hook or render different components. Disabling StrictMode → make the code symmetric."
        }
      }
    },
    "react/thinking-in-react": {
      "quiz": {
        "tir-three-steps": {
          "correctLabel": "B",
          "explanation": "(1) Trigger: a state setter enqueues a render (or it's the initial mount). (2) Render:\nReact calls your component functions top-down and collects element trees — no DOM\nwork, allowed to be interrupted, discarded, or run twice because it has no observable\nside effects. (3) Commit: React diffs the new tree against the previous one\n(reconciliation by element `type` and `key`) and applies the minimal set of DOM\nmutations in one synchronous pass.\n",
          "validLabels": [
            "A",
            "B",
            "C",
            "D"
          ]
        },
        "tir-renders-vs-commits": {
          "correctLabel": "B",
          "explanation": "Renders are cheap, commits are expensive — and React already minimizes commits for\nyou. The diff in the commit phase finds no element-level differences, so the DOM\nisn't touched. This is also why the fix for slow apps is rarely 'prevent renders' —\nit's 'make renders pure and cheap' so the Compiler can memoize them and React can\nskip the work entirely.\n",
          "validLabels": [
            "A",
            "B",
            "C",
            "D"
          ]
        },
        "tir-three-questions": {
          "correctLabel": "B",
          "explanation": "The interrogation: (1) Does it change over time? — if no, it's a constant. (2) Is it\npassed in as a prop? — if yes, it's not state. (3) Is it computable from something\nelse? — if yes, derive it during render. The article's walkthrough table has five\ncandidate data points; only two survive all three tests. Every entry you wrongly\npromote to state becomes a synchronization job you now own.\n",
          "validLabels": [
            "A",
            "B",
            "C",
            "D"
          ]
        },
        "tir-lowest-common-parent": {
          "correctLabel": "B",
          "explanation": "Lift only when shared, and no further than the lowest common parent. Every level you\nlift widens the subtree that re-renders per change and couples components that didn't\nneed coupling. This is the same habit as 'colocate state; lift only when shared.'\nThe walkthrough's `FilterableProductTable` is the example: `SearchBar` displays\n`query`/`inStockOnly`, `ProductTable` consumes them via filtering, and the lowest\ncommon parent is `FilterableProductTable` — not `App`, not context.\n",
          "validLabels": [
            "A",
            "B",
            "C",
            "D"
          ]
        },
        "tir-derived-state-effect": {
          "correctLabel": "B",
          "explanation": "The tell is `useEffect` + `setState` where the effect's only inputs are other\nstate/props. Delete the `visibleCount` state, compute it inline:\n`const visibleCount = products.filter(p => p.inStock).length`. One source of\ntruth, one projection, no extra render. The 'but the computation is expensive'\nobjection is the Compiler-era answer: write it plainly, the Compiler caches it when\ninputs haven't changed, and the profiler will tell you if a hotspot remains.\n",
          "validLabels": [
            "A",
            "B",
            "C",
            "D"
          ]
        }
      },
      "dragdrop": {
        "tir-classify-mistakes": {
          "sidecarId": "tir-classify-mistakes",
          "mode": "exact",
          "slots": [
            {
              "id": "tir-slot-mutate",
              "label": "New reference",
              "accepts": [
                "tir-chip-push",
                "tir-chip-sort"
              ]
            },
            {
              "id": "tir-slot-dom",
              "label": "Use state or ref",
              "accepts": [
                "tir-chip-querysel",
                "tir-chip-classlist"
              ]
            },
            {
              "id": "tir-slot-effect",
              "label": "Move to handler/effect",
              "accepts": [
                "tir-chip-fetch",
                "tir-chip-localstorage"
              ]
            }
          ],
          "chips": [
            {
              "id": "tir-chip-push",
              "text": "`items.push(newItem); setItems(items)`",
              "correctSlots": [
                "tir-slot-mutate"
              ]
            },
            {
              "id": "tir-chip-sort",
              "text": "`arr.sort(); setArr(arr)`",
              "correctSlots": [
                "tir-slot-mutate"
              ]
            },
            {
              "id": "tir-chip-querysel",
              "text": "`document.querySelector('.x').focus()` in render",
              "correctSlots": [
                "tir-slot-dom"
              ]
            },
            {
              "id": "tir-chip-classlist",
              "text": "`document.body.classList.add('open')` in render",
              "correctSlots": [
                "tir-slot-dom"
              ]
            },
            {
              "id": "tir-chip-fetch",
              "text": "`fetch('/api')` in render body",
              "correctSlots": [
                "tir-slot-effect"
              ]
            },
            {
              "id": "tir-chip-localstorage",
              "text": "`localStorage.setItem(...)` in render body",
              "correctSlots": [
                "tir-slot-effect"
              ]
            }
          ],
          "explanation": "Mutating state in place → new reference (`[...items, newItem]`). Expecting immediate update → read the snapshot or use the updater function. Storing derived data → compute it during render. Touching the DOM behind React's back → use state, or refs for focus/measurement. Side effects during render → move them to event handlers or effects. Copying props into state → render from the prop directly."
        }
      }
    }
  }
} as const;

export type QuizAnswerKey = {
  correctLabel: string;
  explanation: string;
  validLabels: string[];
};

export type DragDropAnswerKey = {
  sidecarId: string;
  mode: 'exact' | 'ordered';
  slots: ReadonlyArray<{ id: string; label?: string; accepts: string[] }>;
  chips: ReadonlyArray<{ id: string; text: string; correctSlots: string[] }>;
  explanation: string;
};

export type ArticleAnswerEntry = {
  readonly quiz: Readonly<Record<string, QuizAnswerKey>>;
  readonly dragdrop: Readonly<Record<string, DragDropAnswerKey>>;
};

export type AnswerKeysModule = {
  readonly articleUids: readonly string[];
  readonly byArticle: Readonly<Record<string, ArticleAnswerEntry>>;
};
// The cast below widens the narrow literal-keyed, deeply-readonly
// shape that JSON.stringify + `as const` produce into the loose
// Record<string, …> shape that the server actions need. The
// runtime values are identical — only the static type changes.
export const answerKeysByArticle = answerKeys.byArticle as unknown as Readonly<Record<string, ArticleAnswerEntry>>;
