import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * `users` table — D26 first slice (Google OAuth login).
 *
 * Design notes (see `entities/user.entity.ts`):
 *   - PK is a uuid, generated by `gen_random_uuid()` (the `pgcrypto`
 *     extension is enabled by the scaffold migration).
 *   - `google_sub` carries the Google `sub` claim and is the canonical
 *     login key. Unique-indexed.
 *   - `email` is unique but nullable; Google may not always return one.
 *   - No `password_hash` — Google is the only provider this slice covers.
 *
 * This migration is hand-written because `apps/api/package.json`'s
 * `migration:generate` script is intentionally a non-CLI exit-1 reminder;
 * the convention is hand-roll migrations, never `typeorm migration:generate`.
 */
export class CreateUsers1700000001000 implements MigrationInterface {
  name = 'CreateUsers1700000001000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS users (
        id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        google_sub  varchar(64)  NOT NULL,
        email       varchar(256),
        name        varchar(256),
        avatar_url  text,
        locale      varchar(16),
        created_at  timestamptz  NOT NULL DEFAULT now(),
        updated_at  timestamptz  NOT NULL DEFAULT now()
      )
    `);
    await queryRunner.query(
      `CREATE UNIQUE INDEX IF NOT EXISTS "uq_users_google_sub" ON users (google_sub)`,
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX IF NOT EXISTS "uq_users_email" ON users (email)
       WHERE email IS NOT NULL`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX IF EXISTS "uq_users_email"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "uq_users_google_sub"`);
    await queryRunner.query(`DROP TABLE IF EXISTS users`);
  }
}
